name: Alioss Integration Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
    - ".github/workflows/alioss-integration.yml"
    - "alioss/**"
    - "go.mod"
    - "go.sum"
  push:
    branches:
      - main

jobs:
  alioss-general-integration-tests:
    name:  Alioss General Integration Tests
    runs-on: ubuntu-latest
    # Skip forks and Dependabot (no access to secrets)
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Set up Aliyun CLI
        uses: aliyun/setup-aliyun-cli-action@v1
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest
      - name: Setup Alioss Test Environment
        run: |
            export access_key_id="${{ secrets.ALI_ACCESS_KEY_ID }}"
            export access_key_secret="${{ secrets.ALI_ACCESS_KEY_SECRET }}"
            ./.github/scripts/alioss/setup.sh
      - name: Run Tests
        run: |
            export access_key_id="${{ secrets.ALI_ACCESS_KEY_ID }}"
            export access_key_secret="${{ secrets.ALI_ACCESS_KEY_SECRET }}"
            ./.github/scripts/alioss/run-int.sh
      - name: Teardown Alioss Test Environment
        if: always()
        run: |
            export access_key_id="${{ secrets.ALI_ACCESS_KEY_ID }}"
            export access_key_secret="${{ secrets.ALI_ACCESS_KEY_SECRET }}"
            ./.github/scripts/alioss/teardown.sh